# docker-compose.yml
version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: uvicorn-backend
    privileged: true
    devices:
      - "/dev/gpiochip0:/dev/gpiochip0"
      - "/dev/gpiochip4:/dev/gpiochip4"
      - "/dev/gpiochip10:/dev/gpiochip10"
      - "/dev/gpiochip11:/dev/gpiochip11"
      - "/dev/gpiochip12:/dev/gpiochip12"
      - "/dev/gpiochip13:/dev/gpiochip13"
      - "/dev/gpiomem0:/dev/gpiomem0"
      - "/dev/gpiomem1:/dev/gpiomem1"
      - "/dev/gpiomem2:/dev/gpiomem2"
      - "/dev/gpiomem3:/dev/gpiomem3"
      - "/dev/gpiomem4:/dev/gpiomem4"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: react-frontend
    ports:
      - "5173:5173" # Changed from 5173:80
    volumes:
      - ./frontend/react-ui:/app # Enable hot reload
      - /app/node_modules # Prevent overwriting node_modules
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
